version: '3.5'

services:
  ayo.technicaltest.webapi:
    image: ayotechnicaltestwebapi:dev
    container_name: aYo.TechnicalTest.Webapi
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "aYo.TechnicalTest.Webapi"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_ayo.technicaltest.webapi$
    volumes:
      - C:\work\Mncwango\aYo.TechnicalTest.Webapi\aYo.TechnicalTest.Webapi:/app
      - C:\work\Mncwango\aYo.TechnicalTest.Webapi\aYo.TechnicalTest.Webapi:/src
      - C:\Users\celimpilom\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_ayo.technicaltest.webapi$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_ayo.technicaltest.webapi$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true